### ISSUE TITLE
Question:  What do these mean?

### ISSUE THREAD

**Issue by troyBORG** [db0/AI-Horde#121]
Server https://stablehorde.net has no valid generations for us to do. Skipped Info: {'untrusted': 16}.

WARNING    | 2023-01-08 17:14:54.767933 | worker.bridge_data.stable_diffusion:reload_data:114 - Dynamic models enabled. Please setup creds.py so it won't prompt for authentication later

I noticed in the creds.py it shows username and password.  But I only know of our working name and API key.  I'm guessing there is something different I need for this?

**Comment by db0** [comment]
> Server https://stablehorde.net/ has no valid generations for us to do. Skipped Info: {'untrusted': 16}.

It means your worker didn't find something to pick up and it was skipped 16 times because they requested a trusted worker.

> WARNING | 2023-01-08 17:14:54.767933 | worker.bridge_data.stable_diffusion:reload_data:114 - Dynamic models enabled. Please setup creds.py so it won't prompt for authentication later

>WARNING | 2023-01-08 17:14:54.767933 | worker.bridge_data.stable_diffusion:reload_data:114 - Dynamic models enabled. Please setup creds.py so it won't prompt for authentication later

This means either you huggingface usermame/password of huggingface API.
