### ISSUE TITLE
Expose prompt blacklist regexes as an API endpoint

### ISSUE THREAD

**Issue by natanjunges** [db0/AI-Horde#127]
More specifically, `BLACKLIST1A`, `BLACKLIST1B` and `BLACKLIST2A` (and other ones that eventually are added). This would allow AI Horde clients to highlight and warn about the blacklisted words before submitting the request, thus preventing the user from being reported as suspicious, getting timed out or even banned. This would also help users follow the terms of service.

**Comment by db0** [comment]
Unfortunately I can't do that. These blacklists are there to filter only CP with regex and slow down people trying to bypass it with IP bans. If I expose the regex, then it will be trivial to bypass it, defeating the purpose. Sadly there's still too many dedicated creeps trying to send unethical prompts to the horde and they ruin everything.

We can revert IP bans btw and usually do it when people ask, but this adds a manual step in the process which is also a way to discourage actual creeps.
