### ISSUE TITLE
Generation Already Submitted error when submitting generations

### ISSUE THREAD

**Issue by natanjunges** [db0/AI-Horde#130]
This happens because https://github.com/db0/AI-Horde/blob/6721de190f0384985c4817dd90a82f6f7505e00f/horde/apis/v2/v2.py#L539 returns 0.

**Comment by db0** [comment]
Yep, just fixed. Thanks

**Comment by natanjunges** [comment]
Still getting this error.

**Comment by db0** [comment]
what kind of payload are you submitting?

**Comment by db0** [comment]
Yes int should work. Weird that's returning the payload already submitted error

**Comment by natanjunges** [comment]
I tried sending the seed as int and got the same result.

**Comment by db0** [comment]
there must be something funky with this bridge code and the way it sends the submit. Is it possible to give me the exact submit payload?

**Comment by natanjunges** [comment]
The payload is generated by [this](https://github.com/sdwebui-w-horde/sd-webui-stable-horde-worker/blob/6184f96dd99d03cc8b3f8c4c133e08ae07ce074f/stable_horde.py#L300-L304). I also tried this [other worker](https://github.com/hordeautowebworker/hordeautowebworker.github.io/blob/71ecece205fcb5e41a9aca8ac393f741dd9b5212/index.html#L835-L840), and got the same result. I'm starting to think that the issue might be my user. I noticed that since I created it, the number of kudos is fixed at 25, regardless of how many images I generate.

**Comment by db0** [comment]
What is your horde user ID?

**Comment by db0** [comment]
So looking at the code, the error is not necessarily "Generation Already Submitted". It's just that this client just returns this message [for any error](https://github.com/sdwebui-w-horde/sd-webui-stable-horde-worker/blob/6184f96dd99d03cc8b3f8c4c133e08ae07ce074f/stable_horde.py#L317). This needs to be updated to report the actual error from the horde to help us understand where it's going wrong.

**Comment by db0** [comment]
Also reminder that these are unofficial extensions that I can't realistically troubleshoot. If the official horde worker worker is working, then there must be by necessity a bug in the way these bridges are sending the submit payload

**Comment by natanjunges** [comment]
> What is your horde user ID?

6307, and I managed to earn kudos using the official worker for interrogation, so at least I know I *can* earn them.

> So looking at the code, the error is not necessarily "Generation Already Submitted". It's just that this client just returns this message [for any error](https://github.com/sdwebui-w-horde/sd-webui-stable-horde-worker/blob/6184f96dd99d03cc8b3f8c4c133e08ae07ce074f/stable_horde.py#L317). This needs to be updated to report the actual error from the horde to help us understand where it's going wrong.

Not *any* error, just error 400. I changed my local version to also print the error message sent by the horde, and it is indeed sending a [DuplicateGen](https://github.com/db0/AI-Horde/blob/ff16b04d246a8540aa13c4b6a33adae431454b7d/horde/apis/exceptions.py#L205). I was further investigating this error and I noticed that, due to my hardware being too weak (2GB VRAM GPU, 8GB RAM), the generation takes 5+min to complete, at which point the job might be being considered stale by the horde and being assigned to another worker. But if that's the case, the error code [should be 404](https://github.com/db0/AI-Horde-Worker/blob/05de2be610a4a532702caa71e8f14df183c3059c/worker/jobs/framework.py#L114), not 400.

**Comment by db0** [comment]
OK first thing: Don't onboard a worker which takes 5+ min to complete an image :D You can become an interrogation worker instead though.

About the error, yes a gen that was faulted sends the same errors as one that was completed. I'll see if I can tweak this
