### ISSUE TITLE
Question: how to report error to the horde server

### ISSUE THREAD

**Issue by MaikoTan** [db0/AI-Horde#143]
Hello! I am the main developer of the third-party worker bridge [sd-webui-stable-horde-worker](https://github.com/sdwebui-w-horde/sd-webui-stable-horde-worker).

I faced a question when the worker was generating an image, it might throw exceptions in the generation, if the worker restarted the generation but still got an error, it would try to "drop" this errored job.
But I didn't see there is a way to submit an error that says something like "I can't do this" to the server. So what can I do? Just ignore the errored job or should I try to submit something?

**Comment by db0** [comment]
for now yes, I plan to add a way for the worker to report a faulted job but
haven't gotten around to it yet.

**Comment by db0** [comment]
This has now been implemented on the AI Horde Worker
