### ISSUE TITLE
Kobold Horde Kudos Calculations is incorrect

### ISSUE THREAD

**Issue by LostRuins** [db0/AI-Horde#157]
All models are now returning the default amount of kudos per generation (multiplier=1)  even for larger models that are found on HuggingFace. Perhaps the stats db could be corrupt.

**Comment by LostRuins** [comment]
To add on - it also seems like the "Trusted" status of workers is bugged as every single worker is now appearing as Trusted, even random ones that just popped up.

**Comment by db0** [comment]
Closed with merge to AI Horde
