### ISSUE TITLE
Updated VAE for runwayml stable_diffusion 1.5 inpainting model

### ISSUE THREAD

**Issue by wolfgangmeyers** [db0/AI-Horde#162]
These are pretty easy to update for the `.ckpt` model. Can I upload to huggingface and point workers to the updated model?

**Comment by db0** [comment]
Please open this issue in this repo https://github.com/Sygil-Dev/nataili-model-reference

**Comment by wolfgangmeyers** [comment]
I just found out it uses diffusers. Is it possible to use non-diffusers inpainting?

**Comment by db0** [comment]
Sure, if you send a PR ;)
