### ISSUE TITLE
How would I create a Private Horde?

### ISSUE THREAD

**Issue by Hellisotherpeople** [db0/AI-Horde#178]
I have a use-case which involves using this to create a Stable-Diffusion cluster on some machines that I don't want to connect to the internet. You mention in the FAQ that this is possible, but I see no instructions about this. How would one go about doing this?

**Comment by db0** [comment]
Please check contributing.md

**Comment by tazlin** [comment]
I recently got a development instance up and running, I had to make some specific adjustments (which I made in mind for developing on top of it to contribute back). You can see the [diff in my fork here](https://github.com/db0/AI-Horde/compare/main...tazlin:AI-Horde:local-dev-friendly).

Also of note, out of the box, this project relies on AWS or AWS-style S3 buckets to serve images back to the requestor - you may need to consider posting the images directly as base64 or some similar scheme.

**Comment by db0** [comment]
I'm closing this issue, ok?
