### ISSUE TITLE
"me" endpoint

### ISSUE THREAD

**Issue by wolfgangmeyers** [db0/AI-Horde#183]
Can we get an endpoint like `/v2/me` that returns the same as `/v2/users/{user_id}` for the owner of the api key? I'd like to add the ability for users to input only their api key to my site but still identify them and show their user stats without them also entering their user id.

**Comment by wolfgangmeyers** [comment]
happy to add a PR for this when I have time (probably soon)

**Comment by db0** [comment]
already exists in `/api/v2/find_user`
