### ISSUE TITLE
More control over interrogator

### ISSUE THREAD

**Issue by wolfgangmeyers** [db0/AI-Horde#212]
Currently I have a use case where I need to upscale images that are up to 1024x1280 in size. If these requests go through the interrogate api, they often hit slow workers and take several minutes to complete. I'd like to be able to restrict these requests to only run on my own workers.

**Comment by db0** [comment]
I plan to onboard the same slow_workers feature here as well as I have in the main branch.

**Comment by db0** [comment]
slow_workers option has been onboarded
