### ISSUE TITLE
Client feedback for warning-level problems

### ISSUE THREAD

**Issue by wolfgangmeyers** [db0/AI-Horde#214]
I occasionally see non-fatal issues pop up in the worker logs. These show up as warnings, and don't fail the generation, but they indicate some kind of client bug. Would be good to include a way of providing feedback to the client along with the generation results. Example:

```
Source image/mask mismatch. Resizing mask from (512, 512) to (473, 582)
```
The expectation would be that developers of client applications would monitor warning messages in the generation results, turning silent errors into something that can be fixed.

**Comment by db0** [comment]
This is for https://github.com/db0/AI-Horde-Worker

But wait for the next release before opening it as we're changing a lot in the logging
