### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by leszekhanusz** [db0/AI-Horde#22]
I'm trying to implement the Stable Horde API for the [diffusion-ui](https://github.com/leszekhanusz/diffusion-ui) frontend.

Using the `https://stablehorde.net/api/v2/generate/sync` endpoint, my POST data looks like this:

```
  {
    "payload": {
        "sampler_name": "k_lms",
        "batch_size": 1,
        "cfg_scale": 7,
        "seed": -1,
        "height": 512,
        "width": 512,
        "steps": 50,
        "n": 1
    },
    "prompt": "a horde of cute stable robots in a sprawling server room repairing a massive mainframe",
    "nsfw": false,
    "censor_nsfw": false
  }
```

It seems I was able to receive a few images, but now sometimes I receive the following error:

```
Access to fetch at 'https://stablehorde.net/api/v2/generate/sync' from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by leszekhanusz** [comment]
It seems the error is returned about 3 minutes after the request has been made.

**Comment by db0** [comment]
Any idea what header I need to allow to fix this?

**Comment by leszekhanusz** [comment]
[Access-Control-Allow-Origin: *](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin)

**Comment by db0** [comment]
It seems I'm already allowing that: https://github.com/db0/AI-Horde/blob/main/horde/__init__.py#L33

**Comment by db0** [comment]
I've put the header in my reverse proxy as well. Maybe it will work for you now?

**Comment by leszekhanusz** [comment]
No, here is my console.log value:

```
Access to fetch at 'https://stablehorde.net/api/v2/generate/sync' from origin 'http://localhost:5173' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by db0** [comment]
welp! OK removed it from apache. Did it stop failing immediately now?

**Comment by leszekhanusz** [comment]
Yes, it seems to work again.

**Comment by db0** [comment]
But still randomly failing?

**Comment by db0** [comment]
Anyway, I suggest you use async instead, as it will allow you to get the status of the request while waiting as well

**Comment by leszekhanusz** [comment]
> But still randomly failing?

Difficult to know. It was failing previously when the number of workers were low and after 3 minutes. It seems to work correctly right now. I suspect it fails only when it has to send an error.

**Comment by leszekhanusz** [comment]
> Anyway, I suggest you use async instead, as it will allow you to get the status of the request while waiting as well

Yes, I was planning to switch to async once it works correctly in sync mode.

**Comment by db0** [comment]
It sounds like it was failing because the request was expiring. It should be better now as I increased the expiry timeout to give more time during high load. Async would avoid this.
