### ISSUE TITLE
interrogate/async source_image only takes a url

### ISSUE THREAD

**Issue by Skquark** [db0/AI-Horde#220]
I'm trying to get the REST API to work in my Python app, and I got most things working, but ran into a snag while trying to set the source_image for interrogation.  In the v2/generate/async call, the source_image & source_mask takes a Base64 encoded string, but with v2/interrogate/async call, source_image only takes a public url string.  Not sure if there was a reason for that, however it's not really practical (or doable) to do that from an uploaded image on desktop or Colab app.  Any way to revise it to take the base64 string there?

As a side note, it's not really clear in the api docs what goes into the forms - payload - * - additionalProp fields.  I assume we don't have to give any payload there, but curious what would go there.  Thanks...

**Comment by db0** [comment]
Alchemy accepts a b64 image as well. Check my python cli here as an example: https://github.com/db0/AI-Horde-CLI/blob/main/cli_request_alchemy.py
