### ISSUE TITLE
New responsive frontend now available at diffusionui.com

### ISSUE THREAD

**Issue by leszekhanusz** [db0/AI-Horde#29]
I implemented the Stable Horde async rest api on my [diffusion-ui frontend](https://github.com/leszekhanusz/diffusion-ui).

Advantages over the current web client:
 * works under Firefox
 * you can save the images, they are stored in the browser (until you close your browser) in a gallery in the right panel
 * it's a responsive design, allowing you to use it on your smartphone
 * regenerating same images (to try with a parameter a bit changed for example) is very easy

To use it:
* go to https://diffusionui.com
* open the panel on the left
* select `Stable Horde` in the dropdown at the top
* optionally you can set your api key in the model info tab (ⓘ icon)

Send me a [GitHub star](https://github.com/leszekhanusz/diffusion-ui) if you like it!

**Comment by db0** [comment]
Very cool! Thanks for this. As I said in discord, please provide me with a URL which would default to Stable Horde along with dpms at 30 steps, and I'll link to it!
