### ISSUE TITLE
Crash when nsfw = false and censor_nsfw = true and toggles defined

### ISSUE THREAD

**Issue by barshag** [db0/AI-Horde#54]
When invoking:

 curl -X 'POST' \
  'https://stablehorde.net/api/v2/generate/async' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'apikey:0000000000' \
  -d '{
  "prompt": "parrot dancing in room",
  "params": {
    "sampler_name": "k_lms",
    "toggles": [
      1,
      4
    ],
    "realesrgan_model_name": "string",
    "ddim_eta": 0,
    "batch_size": 1,
    "cfg_scale": 5,
    "seed": "string",
    "height": 512,
    "width": 512,
    "fp": 512,
    "variant_amount": 0,
    "variant_seed": 0,
    "steps": 50,
    "n": 1
  },
  "nsfw": false,
  "trusted_workers": true,
  "censor_nsfw": true,
  "workers": [
    "string"
  ]
}'

Get an error:  {"message": "Internal Server Error"}

**Comment by db0** [comment]
It is correct. There's just a bug. It'll be fixed in the next deploy. Thanks
