### ISSUE TITLE
Switch the AI Horde from in-memory dictionaries, to a DB

### ISSUE THREAD

**Issue by db0** [db0/AI-Horde#55]
With the rapid growth of the Stable Horde, this might become necessary sooner than later. 

The current build is just storing users and workers in memory as python dicts. But as our users reach thousands or more, this might become unfeasible.

So I want to plan ahead and start developing the way to store user and worker objects to a Redis DB instead. I have a lot of other features that have more priority though, so I want some help!

If someone sends me a PR for this, there's a 500K Kudos bounty attached: https://discord.com/channels/781145214752129095/1028974305326932020/1028974305326932020

**Comment by skyrina** [comment]
wont this have the same exact issue? redis is an in-memory database, meaning that the entire database is stored in ram and saved on disk every few minutes.
i believe something like mongodb/mariadb/postgres/cassandra/whatever would work a lot better for this

**Comment by db0** [comment]
I am not married to redis tbh. This is why I renamed this topic. But having the DB in redis, will allow me to put redis elsehwere and then have multiple frontend nodes access it and offload the crunching and bandwidth parts. 

My Db is not particularly large anyway, so having it in RAM is not a big deal.

**Comment by ndahlquist** [comment]
Is this issue related to the Jina refactor, or totally parallel? (I'd love to get a better understanding of the dev roadmap and where things are at, to see if there's anywhere I can contribute).

I'm wondering if we've considered something like pub/sub or Kafka? (I don't have much experience with either, but understand that they are popular technologies for job scheduling/queuing).

**Comment by db0** [comment]
This has nothing to do with Jina. That is an API some sygil devs are working for Nataili (the backend of nataili). This is about the Stable Horde.

**Comment by ndahlquist** [comment]
Ah got it, that makes sense; I wasn't sure how Jina was involved. Glad to know it is totally separate from the stable horde.

Then my question is just have we considered Kafka or pub/sub for the Stable Horde queue? It seems like it could potentially solve a few issues:
- High availability.
- Most likely higher performance / lower latency. Currently I'm seeing ~1s to queue a task, and >1 second to pop a task, so I imagine the end to end latency might be greater than 2s?
- No more race conditions with dequeuing.
- Possibly others (not sure).

I'd be happy to do an investigation and put together a list of pros and cons if that would be useful @db0 ?

**Comment by db0** [comment]
To use a queue system, I need the queue to support custom sorting mechanism. Does Kafka do that?

The current delays are because the system is generally overloaded anyway.

**Comment by ndahlquist** [comment]
Good point; I think Kafka is for FIFO queueing, so I suppose not appropriate for this use case.
