### ISSUE TITLE
Joining the horde with a 4GB GPU

### ISSUE THREAD

**Issue by llagerlof** [db0/AI-Horde#56]
My GPU is a NVIDIA 1050Ti with 4GB. My PC has 16GB memory. I can run some, but not all, stable diffusion projects.

Can I join the horde as a worker with those specs? Is there a "minimum requirements" to run the worker?

**Comment by db0** [comment]
I think you probably can, but you should limit your generations to 512x512 only. Generally if your worker goes lower than 0.2 Megapixelsteps per second, it is going to be frustrating for people waiting for their generations and we want to avoid that.
