### ISSUE TITLE
Selecting the 'streamlit' option when starting the webui ignores the --bridge option.

### ISSUE THREAD

**Issue by CrypticWit** [db0/AI-Horde#58]
When launching the sd-webui with webui.sh/bat, the user is now queried as to whether they wish to launch the gradio or streamlit version.  It seems that the streamlit version (webui_streamlit.py) of the sd-webui doesn't support the '--bridge' flag.

The documentation might need a quick update in the 'Join the Horde' section to note this is the case, or the webui_streamlit.py script updated to properly launch in bridge mode.

**Comment by db0** [comment]
I'm working on a more lightweight worker code at the moment. But also `horde_bridge.sh/cmd` already exists which opens the bridge directly.
