### ISSUE TITLE
Other webui repository support?

### ISSUE THREAD

**Issue by DumoeDss** [db0/AI-Horde#60]
Hey, Can you add support for this repository?
https://github.com/AUTOMATIC1111/stable-diffusion-webui
This repository is currently being updated very frequently, is very powerful and has a very large number of users.

**Comment by db0** [comment]
Hello, this is not in my hands. The developers of that UI have to add this support. I see you've already found https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/1449 so please ask the relevant people to add this.

**Comment by 0xdevalias** [comment]
>  > I am also open for advice on where I could plug in the bridge myself.
> 
> @db0 Given the improved support for external extensions now, I think this would probably be the perfect way to go about integrating StableHorde with this web ui:
> 
> - https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Developing-extensions
> - https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Custom-Scripts
> 
> Then you could get it added to the index, and it should be a 1 click install for any users who want it:
> 
> - https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Extensions-index
> 
> ![image](https://user-images.githubusercontent.com/753891/200150894-7839aab2-3d9b-4e1e-a5ab-9ca83f95851d.png)
> 
> _Originally posted by @0xdevalias in https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/1449#issuecomment-1304697849_
