### ISSUE TITLE
Inpainting on cliRequests.py

### ISSUE THREAD

**Issue by hannibalbarx** [db0/AI-Horde#75]
i've tried various types of masks but no luck.

i assume the mask image needs to be transparent where it is to be inpainted.

it just seems to create a new image

**Comment by hannibalbarx** [comment]
also the denoising strength can only be set in the file, no cmd line parameter

**Comment by db0** [comment]
Are you using cliRequest.py?

If so, you either need to send a black&white mask as the example files. Or you need to send only the source image with transparency. The source_processing has to be as "inpainting"

**Comment by hannibalbarx** [comment]
does the model have to be stable_diffusion_inpainting ? because that model always times out. (i have tried countless times through the day. StableUI is able to run that model no problems. (but you can't upload masks to StableUI)

**Comment by hannibalbarx** [comment]
this is the message it dies with:

`ERROR      | 2022-11-03 17:17:49 | __main__:generate:133 - {"message": "Request with ID '0ecdcee0-1a66-40d0-8bfd-e6f1984f546b' not found."}`

**Comment by db0** [comment]
Yes the model has to be stable_diffusion_inpainting.

So you **are** using `cliRequest.py`?

**Comment by hannibalbarx** [comment]
`python ~/Stable-Horde/cli_request.py -n 2 -p "a royal bedroom by Mark Ryden, cgsociety contest winner, pop surrealism, daz3d, polycount, deviantart hd" -f image`ls -al|wc -l`.png --source_image bella2_mask2.png --source_processing inpainting`

**Comment by db0** [comment]
your input is wrong. Did you try to use `cliRequestsData.py` instead? It's commnented
