### ISSUE TITLE
Incorrect kudos error message for "too many steps"

### ISSUE THREAD

**Issue by mryellow** [db0/AI-Horde#76]
Request: `512x512`, Steps: `51`

`ERROR: Error received from the Stable Horde: For requests over 1024x1024 or over 100 steps, the client needs to already have the required kudos. This request requires 857.4 kudos to fulfil`

Client: `v0.10.0`

Seems it will error on `steps > 50` but describes the error as `100`.

**Comment by db0** [comment]
This is due to your sampler. k_heun and k_dps sampler do double the steps by default. The UI you're using needs to be updated to make this obvious.
