### ISSUE TITLE
server:  api /v2/generate/sync returned a 504 error

### ISSUE THREAD

**Issue by MirrorCY** [db0/AI-Horde#88]
Hi i'm MirrorCY#2974, thank you for making such a great platform for everyone to draw for free 🚀 
English is not my native language; please excuse typing errors.

Last about 24 hours `https://stablehorde.net/api/v2/generate/sync` interface is down and it returns `504 The server didn't respond in time`.
I've tried to change to a different network but the issues same.
At the same time, the interface `/v2/generate/async` works well.

**Comment by db0** [comment]
Can you tell me what doesn't work well with async? Everyone else is using it

**Comment by MirrorCY** [comment]
Async is good!
But I was just starting to learn programming, and sync was more in line with noob's intuition, so I chose it 😢
