### ISSUE TITLE
Dynamic Workers causing models to show 0 workers and thus be unavailable

### ISSUE THREAD

**Issue by ResidentChief** [db0/AI-Horde#95]
With the dynamic workers not reporting all of the models, /status/models endpoint is not reporting some models despite being available (after delay)

I think /horde/database/functions.py get_available_models needs to fetch the db.json from nataili_model_manager (or there needs to be a table added to the db updated periodically with that content), strip out the upscalers etc, then for each model in that list, get the details from the db and return the full list.

Then it's up to the UIs to inform the users that the model has 0 workers with it loaded and it'll take ~5 mins to load before processing..

**Comment by db0** [comment]
That's already possible. It's a frontend task

**Comment by ResidentChief** [comment]
I can see that - but shouldn't the models endpoint contain all the data about models rather than just current models?

**Comment by db0** [comment]
No, that's not the job of the horde as the list of models is not set from its perspective.

**Comment by ResidentChief** [comment]
All good, will close and reopen in the StableUI github

**Comment by db0** [comment]
You can close your own issues ;)
